# name字段是 workflow 的名称
name: GitHub Actions Build and Deploy Demo
# on字段指定触发 workflow 的条件，通常是某些事件
# 这里的触发条件是push代码到master的时候触发
on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]

    # checkout@ 这里写你的分支名称
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        run: npm -g install pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate
        run: pnpm build

      - name: Publish
        uses: cpina/github-action-push-to-another-repository@v1.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source-directory: "dist"
          destination-github-username: "shouzia"
          destination-repository-name: "Myweb-Aaboutme"
          user-email: saopipizhu@163.com
          target-branch: "git-page"
